**** Function test ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ ]
	          live: 2 0
	l         in:   [ s.3 x.4 ]
	          out:  [ s.5 x.6 ]
	          gen:  [ c s.3 x.4 s.5 x.6 s.8 s.9 x.10 ]
	          live: 7 0
	c         in:   [ s.5 x.6 ]
	          out:  [ s.5 x.7 ]
	          gen:  [ s.5 x.6 x.7 ]
	          live: 4 0
	end       in:   [ s.5 ]
	          out:  [ ]
	          gen:  [ s.5 ]
	          live: 1 0

