**** Function alpha ****
> Liveness analysis:
	ini       in:   [ ]
	          out:  [ p l n pe ]
	          gen:  [ p l n pe ]
	          live: 6 0
	lop       in:   [ p n pe p1 l1 ]
	          out:  [ p n pe p2 l2 ]
	          gen:  [ pe p1 p2 l1 l2 ]
	          live: 8 0
	end       in:   [ p n ]
	          out:  [ ]
	          gen:  [ p n ]
	          live: 4 0

**** Function test ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ r0 r1 r2 abi.2 blt.8 blt.11 blt.14 blt.17 blt.20 blt.23 isel.26 isel.27 ]
	          live: 11 15

