**** Function f1 ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ ]
	          live: 1 0

**** Function f2 ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ x isel.1 ]
	          live: 3 0

**** Function f3 ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ x isel.2 ]
	          live: 3 0

**** Function f4 ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ ]
	          live: 1 0

**** Function f5 ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ x ]
	          live: 1 0

**** Function f6 ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ x isel.3 ]
	          live: 3 0

