**** Function test ****
> Liveness analysis:
	start     in:   [ ]
	          out:  [ ]
	          gen:  [ ]
	          live: 2 0
	loop      in:   [ n p ]
	          out:  [ n p p1 ]
	          gen:  [ p p1 ]
	          live: 5 0
	tloop     in:   [ n p p1 t ]
	          out:  [ n p p1 t ]
	          gen:  [ n p p1 t r ]
	          live: 8 0
	next      in:   [ n p p1 t ]
	          out:  [ n p p1 t1 ]
	          gen:  [ p t t1 tsq ]
	          live: 7 0
	yes       in:   [ n p p1 ]
	          out:  [ n1 p p1 ]
	          gen:  [ n n1 p1 ]
	          live: 5 0
	end       in:   [ p ]
	          out:  [ ]
	          gen:  [ p ]
	          live: 3 0

