**** Function strspn_ ****
> Liveness analysis:
	.64       in:   [ ]
	          out:  [ s1.81.val s2.82.val ]
	          gen:  [ s1.81.val s2.82.val ]
	          live: 4 0
	.28       in:   [ s2.82.val .60 n.83.3 s1.81.4 ]
	          out:  [ s2.82.val .60 n.83.3 s1.81.4 ]
	          gen:  [ s2.82.val ]
	          live: 6 0
	.30       in:   [ s2.82.val .60 n.83.3 s1.81.4 p.85.8 ]
	          out:  [ s2.82.val .41 .60 n.83.3 s1.81.4 ]
	          gen:  [ .41 p.85.8 ]
	          live: 7 0
	.29       in:   [ s2.82.val .60 n.83.3 s1.81.4 p.85.8 ]
	          out:  [ s2.82.val .44 .60 n.83.3 s1.81.4 p.85.8 ]
	          gen:  [ .44 p.85.8 ]
	          live: 8 0
	.42       in:   [ s2.82.val .44 .60 n.83.3 s1.81.4 p.85.8 ]
	          out:  [ s2.82.val .44 .60 n.83.3 s1.81.4 p.85.8 ]
	          gen:  [ .44 .60 ]
	          live: 8 0
	.36       in:   [ s2.82.val .44 n.83.3 s1.81.4 ]
	          out:  [ s2.82.val n.83.3 s1.81.4 ]
	          gen:  [ .44 ]
	          live: 6 0
	.37       in:   [ n.83.3 ]
	          out:  [ n.83.3 ]
	          gen:  [ ]
	          live: 3 0
	.33       in:   [ s2.82.val n.83.3 s1.81.4 ]
	          out:  [ s2.82.val .57 .59 ]
	          gen:  [ .57 .59 n.83.3 s1.81.4 ]
	          live: 5 0
	.27       in:   [ s2.82.val n.83.3 s1.81.4 ]
	          out:  [ s2.82.val .60 n.83.3 s1.81.4 ]
	          gen:  [ .60 s1.81.4 ]
	          live: 6 0
	.38       in:   [ n.83.3 ]
	          out:  [ n.83.3 ]
	          gen:  [ ]
	          live: 3 0
	.34       in:   [ n.83.3 ]
	          out:  [ ]
	          gen:  [ n.83.3 ]
	          live: 1 0

